### ISSUE TITLE
Can´t import your crate

### ISSUE THREAD

**Issue by Y0ngg4n** [CodyCline/horcrux-rs#1]
Hi i am trying to create a rust web ui for this, but i can´t import the code. I added it to the Cargo.toml but i still can´t import it, neither with git nor with standard crate. Can you check that please?

**Comment by CodyCline** [comment]
Hey @Y0ngg4n, it looks like this can be done by porting core functions as a separate lib that the rest of the project depends on. The name `horcrux-rs` may have been a source of confusion since usually rust projects ending in `-rs` imply it's a library - my mistake. Let's have the best of both worlds, fix coming soon!

**Comment by CodyCline** [comment]
@Y0ngg4n the new version is published on crates. Upgrade your dep to `1.2.1` and try the following code. Let me know if this works.

```rs
use std::path::PathBuf;

fn main() {
    let split_operation = horcrux_rs::split(
        &PathBuf::from("./treasure_map.txt"), &PathBuf::from("."), 3, 3);
    match split_operation {
        Ok(_) => println!("Treasure map is now split into pieces!"),
        Err(e) => println!("Error occurred splitting the treasure map: {e}")
    }
    println!("Hello, world!");
}

```

**Comment by Y0ngg4n** [comment]
@CodyCline a thanks. 1.2.1 works
